/**
 * Write the Homebrew formula for a release, from its SHA256SUMS. The release workflow runs it and
 * commits the result to the tap.
 *
 *   bun scripts/formula.ts --repo <owner/name> --version <x.y.z> --sums <SHA256SUMS>
 */
import { parseArgs } from "node:util";

/** The binaries a release ships, as `lr-<version>-<os>-<arch>.tar.gz`. */
export const TARGETS = [
  { os: "darwin", arch: "arm64" },
  { os: "darwin", arch: "x64" },
  { os: "linux", arch: "arm64" },
  { os: "linux", arch: "x64" },
] as const;

export type Target = (typeof TARGETS)[number];

export const archiveName = (version: string, t: Target) => `lr-${version}-${t.os}-${t.arch}.tar.gz`;

/** `sha256sum` output (`<hash>  <file>` per line) as file → hash. */
export function parseSums(text: string): Map<string, string> {
  const sums = new Map<string, string>();
  for (const line of text.split("\n")) {
    if (!line.trim()) continue;
    const m = line.match(/^([0-9a-f]{64}) [ *](\S+)$/);
    if (!m) throw new Error(`not a sha256sum line: ${line}`);
    sums.set(m[2]!, m[1]!);
  }
  return sums;
}

export function formula(opts: { repo: string; version: string; sums: Map<string, string> }) {
  const { repo, version, sums } = opts;
  if (!/^[\w.-]+\/[\w.-]+$/.test(repo)) throw new Error(`--repo must be <owner>/<name>: ${repo}`);
  if (!/^\d+\.\d+\.\d+$/.test(version)) throw new Error(`--version must be x.y.z: ${version}`);
  const asset = (t: Target) => {
    const name = archiveName(version, t);
    const sha = sums.get(name);
    if (!sha) throw new Error(`no checksum for ${name}`);
    const url = `https://github.com/${repo}/releases/download/v${version}/${name}`;
    return `      url "${url}"\n      sha256 "${sha}"`;
  };
  const block = (os: Target["os"], arch: Target["arch"]) =>
    asset(TARGETS.find((t) => t.os === os && t.arch === arch)!);

  return `# Generated by scripts/formula.ts in ${repo} for each release. Don't edit it by hand.
class LocalReview < Formula
  desc "Local code review for agentic development, built on jj"
  homepage "https://github.com/${repo}"
  version "${version}"
  license "Unlicense"

  depends_on "jj"

  on_macos do
    on_arm do
${block("darwin", "arm64")}
    end
    on_intel do
${block("darwin", "x64")}
    end
  end

  on_linux do
    on_arm do
${block("linux", "arm64")}
    end
    on_intel do
${block("linux", "x64")}
    end
  end

  def install
    bin.install "lr"
  end

  test do
    assert_match "lr #{version}", shell_output("#{bin}/lr --version")
  end
end
`;
}

export async function main(argv: string[]): Promise<string> {
  const { values } = parseArgs({
    args: argv,
    options: {
      repo: { type: "string" },
      version: { type: "string" },
      sums: { type: "string" },
    },
    strict: true,
  });
  if (!values.repo || !values.version || !values.sums) {
    throw new Error("usage: formula.ts --repo <owner/name> --version <x.y.z> --sums <SHA256SUMS>");
  }
  const sums = parseSums(await Bun.file(values.sums).text());
  return formula({ repo: values.repo, version: values.version, sums });
}

if (import.meta.main) process.stdout.write(await main(Bun.argv.slice(2)));
